apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-frontend
  labels:
    app: feedback-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback-frontend
  template:
    metadata:
      labels:
        app: feedback-frontend
    spec:
      containers:
      - name: feedback-frontend
        image: feedback-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_URL
          value: "http://feedback-backend:8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
